// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: work.proto

#include "work.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace prototask {
template <typename>
PROTOBUF_CONSTEXPR WrapperMessage::WrapperMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.fast_response_)*/nullptr
  , /*decltype(_impl_.slow_response_)*/nullptr
  , /*decltype(_impl_.request_for_fast_response_)*/nullptr
  , /*decltype(_impl_.request_for_slow_response_)*/nullptr} {}
struct WrapperMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WrapperMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WrapperMessageDefaultTypeInternal() {}
  union {
    WrapperMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WrapperMessageDefaultTypeInternal _WrapperMessage_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR FastResponse::FastResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.current_date_time_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }
} {}
struct FastResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FastResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FastResponseDefaultTypeInternal() {}
  union {
    FastResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FastResponseDefaultTypeInternal _FastResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR SlowResponse::SlowResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.connected_client_count_)*/ 0u
} {}
struct SlowResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SlowResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SlowResponseDefaultTypeInternal() {}
  union {
    SlowResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SlowResponseDefaultTypeInternal _SlowResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR RequestForFastResponse::RequestForFastResponse(
    ::_pbi::ConstantInitialized) {}
struct RequestForFastResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestForFastResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestForFastResponseDefaultTypeInternal() {}
  union {
    RequestForFastResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestForFastResponseDefaultTypeInternal _RequestForFastResponse_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR RequestForSlowResponse::RequestForSlowResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.time_in_seconds_to_sleep_)*/ 0u
} {}
struct RequestForSlowResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestForSlowResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestForSlowResponseDefaultTypeInternal() {}
  union {
    RequestForSlowResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestForSlowResponseDefaultTypeInternal _RequestForSlowResponse_default_instance_;
}  // namespace prototask
static ::_pb::Metadata file_level_metadata_work_2eproto[5];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_work_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_work_2eproto = nullptr;
const ::uint32_t TableStruct_work_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::prototask::WrapperMessage, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::prototask::WrapperMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::prototask::WrapperMessage, _impl_.fast_response_),
    PROTOBUF_FIELD_OFFSET(::prototask::WrapperMessage, _impl_.slow_response_),
    PROTOBUF_FIELD_OFFSET(::prototask::WrapperMessage, _impl_.request_for_fast_response_),
    PROTOBUF_FIELD_OFFSET(::prototask::WrapperMessage, _impl_.request_for_slow_response_),
    0,
    1,
    2,
    3,
    PROTOBUF_FIELD_OFFSET(::prototask::FastResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::prototask::FastResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::prototask::FastResponse, _impl_.current_date_time_),
    0,
    PROTOBUF_FIELD_OFFSET(::prototask::SlowResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::prototask::SlowResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::prototask::SlowResponse, _impl_.connected_client_count_),
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::prototask::RequestForFastResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::prototask::RequestForSlowResponse, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::prototask::RequestForSlowResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::prototask::RequestForSlowResponse, _impl_.time_in_seconds_to_sleep_),
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 12, -1, sizeof(::prototask::WrapperMessage)},
        { 16, 25, -1, sizeof(::prototask::FastResponse)},
        { 26, 35, -1, sizeof(::prototask::SlowResponse)},
        { 36, -1, -1, sizeof(::prototask::RequestForFastResponse)},
        { 44, 53, -1, sizeof(::prototask::RequestForSlowResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::prototask::_WrapperMessage_default_instance_._instance,
    &::prototask::_FastResponse_default_instance_._instance,
    &::prototask::_SlowResponse_default_instance_._instance,
    &::prototask::_RequestForFastResponse_default_instance_._instance,
    &::prototask::_RequestForSlowResponse_default_instance_._instance,
};
const char descriptor_table_protodef_work_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\nwork.proto\022\tprototask\"\374\001\n\016WrapperMessa"
    "ge\022.\n\rfast_response\030\001 \001(\0132\027.prototask.Fa"
    "stResponse\022.\n\rslow_response\030\002 \001(\0132\027.prot"
    "otask.SlowResponse\022D\n\031request_for_fast_r"
    "esponse\030\003 \001(\0132!.prototask.RequestForFast"
    "Response\022D\n\031request_for_slow_response\030\004 "
    "\001(\0132!.prototask.RequestForSlowResponse\")"
    "\n\014FastResponse\022\031\n\021current_date_time\030\001 \002("
    "\t\".\n\014SlowResponse\022\036\n\026connected_client_co"
    "unt\030\001 \002(\r\"\030\n\026RequestForFastResponse\":\n\026R"
    "equestForSlowResponse\022 \n\030time_in_seconds"
    "_to_sleep\030\001 \002(\r"
};
static ::absl::once_flag descriptor_table_work_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_work_2eproto = {
    false,
    false,
    455,
    descriptor_table_protodef_work_2eproto,
    "work.proto",
    &descriptor_table_work_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_work_2eproto::offsets,
    file_level_metadata_work_2eproto,
    file_level_enum_descriptors_work_2eproto,
    file_level_service_descriptors_work_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_work_2eproto_getter() {
  return &descriptor_table_work_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_work_2eproto(&descriptor_table_work_2eproto);
namespace prototask {
// ===================================================================

class WrapperMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<WrapperMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(WrapperMessage, _impl_._has_bits_);
  static const ::prototask::FastResponse& fast_response(const WrapperMessage* msg);
  static void set_has_fast_response(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::prototask::SlowResponse& slow_response(const WrapperMessage* msg);
  static void set_has_slow_response(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::prototask::RequestForFastResponse& request_for_fast_response(const WrapperMessage* msg);
  static void set_has_request_for_fast_response(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::prototask::RequestForSlowResponse& request_for_slow_response(const WrapperMessage* msg);
  static void set_has_request_for_slow_response(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
};

const ::prototask::FastResponse&
WrapperMessage::_Internal::fast_response(const WrapperMessage* msg) {
  return *msg->_impl_.fast_response_;
}
const ::prototask::SlowResponse&
WrapperMessage::_Internal::slow_response(const WrapperMessage* msg) {
  return *msg->_impl_.slow_response_;
}
const ::prototask::RequestForFastResponse&
WrapperMessage::_Internal::request_for_fast_response(const WrapperMessage* msg) {
  return *msg->_impl_.request_for_fast_response_;
}
const ::prototask::RequestForSlowResponse&
WrapperMessage::_Internal::request_for_slow_response(const WrapperMessage* msg) {
  return *msg->_impl_.request_for_slow_response_;
}
WrapperMessage::WrapperMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:prototask.WrapperMessage)
}
WrapperMessage::WrapperMessage(const WrapperMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WrapperMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.fast_response_){nullptr}
    , decltype(_impl_.slow_response_){nullptr}
    , decltype(_impl_.request_for_fast_response_){nullptr}
    , decltype(_impl_.request_for_slow_response_){nullptr}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.fast_response_ = new ::prototask::FastResponse(*from._impl_.fast_response_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000002u) != 0) {
    _this->_impl_.slow_response_ = new ::prototask::SlowResponse(*from._impl_.slow_response_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000004u) != 0) {
    _this->_impl_.request_for_fast_response_ = new ::prototask::RequestForFastResponse(*from._impl_.request_for_fast_response_);
  }
  if ((from._impl_._has_bits_[0] & 0x00000008u) != 0) {
    _this->_impl_.request_for_slow_response_ = new ::prototask::RequestForSlowResponse(*from._impl_.request_for_slow_response_);
  }
  // @@protoc_insertion_point(copy_constructor:prototask.WrapperMessage)
}

inline void WrapperMessage::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.fast_response_){nullptr}
    , decltype(_impl_.slow_response_){nullptr}
    , decltype(_impl_.request_for_fast_response_){nullptr}
    , decltype(_impl_.request_for_slow_response_){nullptr}
  };
}

WrapperMessage::~WrapperMessage() {
  // @@protoc_insertion_point(destructor:prototask.WrapperMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WrapperMessage::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.fast_response_;
  if (this != internal_default_instance()) delete _impl_.slow_response_;
  if (this != internal_default_instance()) delete _impl_.request_for_fast_response_;
  if (this != internal_default_instance()) delete _impl_.request_for_slow_response_;
}

void WrapperMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WrapperMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:prototask.WrapperMessage)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.fast_response_ != nullptr);
      _impl_.fast_response_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.slow_response_ != nullptr);
      _impl_.slow_response_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      ABSL_DCHECK(_impl_.request_for_fast_response_ != nullptr);
      _impl_.request_for_fast_response_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      ABSL_DCHECK(_impl_.request_for_slow_response_ != nullptr);
      _impl_.request_for_slow_response_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WrapperMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .prototask.FastResponse fast_response = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_fast_response(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .prototask.SlowResponse slow_response = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_slow_response(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .prototask.RequestForFastResponse request_for_fast_response = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_request_for_fast_response(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .prototask.RequestForSlowResponse request_for_slow_response = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_request_for_slow_response(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* WrapperMessage::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prototask.WrapperMessage)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .prototask.FastResponse fast_response = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::fast_response(this),
        _Internal::fast_response(this).GetCachedSize(), target, stream);
  }

  // optional .prototask.SlowResponse slow_response = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::slow_response(this),
        _Internal::slow_response(this).GetCachedSize(), target, stream);
  }

  // optional .prototask.RequestForFastResponse request_for_fast_response = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::request_for_fast_response(this),
        _Internal::request_for_fast_response(this).GetCachedSize(), target, stream);
  }

  // optional .prototask.RequestForSlowResponse request_for_slow_response = 4;
  if (cached_has_bits & 0x00000008u) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::request_for_slow_response(this),
        _Internal::request_for_slow_response(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prototask.WrapperMessage)
  return target;
}

::size_t WrapperMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prototask.WrapperMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional .prototask.FastResponse fast_response = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.fast_response_);
    }

    // optional .prototask.SlowResponse slow_response = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.slow_response_);
    }

    // optional .prototask.RequestForFastResponse request_for_fast_response = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.request_for_fast_response_);
    }

    // optional .prototask.RequestForSlowResponse request_for_slow_response = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.request_for_slow_response_);
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WrapperMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WrapperMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WrapperMessage::GetClassData() const { return &_class_data_; }


void WrapperMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WrapperMessage*>(&to_msg);
  auto& from = static_cast<const WrapperMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prototask.WrapperMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_mutable_fast_response()->::prototask::FastResponse::MergeFrom(
          from._internal_fast_response());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_mutable_slow_response()->::prototask::SlowResponse::MergeFrom(
          from._internal_slow_response());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_mutable_request_for_fast_response()->::prototask::RequestForFastResponse::MergeFrom(
          from._internal_request_for_fast_response());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_internal_mutable_request_for_slow_response()->::prototask::RequestForSlowResponse::MergeFrom(
          from._internal_request_for_slow_response());
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WrapperMessage::CopyFrom(const WrapperMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prototask.WrapperMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WrapperMessage::IsInitialized() const {
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!_impl_.fast_response_->IsInitialized()) return false;
  }
  if ((_impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!_impl_.slow_response_->IsInitialized()) return false;
  }
  if ((_impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (!_impl_.request_for_slow_response_->IsInitialized()) return false;
  }
  return true;
}

void WrapperMessage::InternalSwap(WrapperMessage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WrapperMessage, _impl_.request_for_slow_response_)
      + sizeof(WrapperMessage::_impl_.request_for_slow_response_)
      - PROTOBUF_FIELD_OFFSET(WrapperMessage, _impl_.fast_response_)>(
          reinterpret_cast<char*>(&_impl_.fast_response_),
          reinterpret_cast<char*>(&other->_impl_.fast_response_));
}

::PROTOBUF_NAMESPACE_ID::Metadata WrapperMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_work_2eproto_getter, &descriptor_table_work_2eproto_once,
      file_level_metadata_work_2eproto[0]);
}
// ===================================================================

class FastResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<FastResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(FastResponse, _impl_._has_bits_);
  static void set_has_current_date_time(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

FastResponse::FastResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:prototask.FastResponse)
}
FastResponse::FastResponse(const FastResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FastResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.current_date_time_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.current_date_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.current_date_time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.current_date_time_.Set(from._internal_current_date_time(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:prototask.FastResponse)
}

inline void FastResponse::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.current_date_time_) {}

  };
  _impl_.current_date_time_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.current_date_time_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FastResponse::~FastResponse() {
  // @@protoc_insertion_point(destructor:prototask.FastResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FastResponse::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.current_date_time_.Destroy();
}

void FastResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FastResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:prototask.FastResponse)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.current_date_time_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FastResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string current_date_time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_current_date_time();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "prototask.FastResponse.current_date_time");
          #endif  // !NDEBUG
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* FastResponse::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prototask.FastResponse)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string current_date_time = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_current_date_time();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "prototask.FastResponse.current_date_time");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prototask.FastResponse)
  return target;
}

::size_t FastResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prototask.FastResponse)
  ::size_t total_size = 0;

  // required string current_date_time = 1;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_current_date_time());
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FastResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FastResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FastResponse::GetClassData() const { return &_class_data_; }


void FastResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FastResponse*>(&to_msg);
  auto& from = static_cast<const FastResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prototask.FastResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_current_date_time(from._internal_current_date_time());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FastResponse::CopyFrom(const FastResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prototask.FastResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FastResponse::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void FastResponse::InternalSwap(FastResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.current_date_time_, lhs_arena,
                                       &other->_impl_.current_date_time_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata FastResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_work_2eproto_getter, &descriptor_table_work_2eproto_once,
      file_level_metadata_work_2eproto[1]);
}
// ===================================================================

class SlowResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<SlowResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(SlowResponse, _impl_._has_bits_);
  static void set_has_connected_client_count(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

SlowResponse::SlowResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:prototask.SlowResponse)
}
SlowResponse::SlowResponse(const SlowResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:prototask.SlowResponse)
}

inline void SlowResponse::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.connected_client_count_) { 0u }

  };
}

SlowResponse::~SlowResponse() {
  // @@protoc_insertion_point(destructor:prototask.SlowResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SlowResponse::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void SlowResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SlowResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:prototask.SlowResponse)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.connected_client_count_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SlowResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required uint32 connected_client_count = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_connected_client_count(&has_bits);
          _impl_.connected_client_count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* SlowResponse::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prototask.SlowResponse)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required uint32 connected_client_count = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_connected_client_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prototask.SlowResponse)
  return target;
}

::size_t SlowResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prototask.SlowResponse)
  ::size_t total_size = 0;

  // required uint32 connected_client_count = 1;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_connected_client_count());
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SlowResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SlowResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SlowResponse::GetClassData() const { return &_class_data_; }


void SlowResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SlowResponse*>(&to_msg);
  auto& from = static_cast<const SlowResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prototask.SlowResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_connected_client_count(from._internal_connected_client_count());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SlowResponse::CopyFrom(const SlowResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prototask.SlowResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SlowResponse::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void SlowResponse::InternalSwap(SlowResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);

  swap(_impl_.connected_client_count_, other->_impl_.connected_client_count_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SlowResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_work_2eproto_getter, &descriptor_table_work_2eproto_once,
      file_level_metadata_work_2eproto[2]);
}
// ===================================================================

class RequestForFastResponse::_Internal {
 public:
};

RequestForFastResponse::RequestForFastResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:prototask.RequestForFastResponse)
}
RequestForFastResponse::RequestForFastResponse(const RequestForFastResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  RequestForFastResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:prototask.RequestForFastResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RequestForFastResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RequestForFastResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata RequestForFastResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_work_2eproto_getter, &descriptor_table_work_2eproto_once,
      file_level_metadata_work_2eproto[3]);
}
// ===================================================================

class RequestForSlowResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<RequestForSlowResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(RequestForSlowResponse, _impl_._has_bits_);
  static void set_has_time_in_seconds_to_sleep(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

RequestForSlowResponse::RequestForSlowResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:prototask.RequestForSlowResponse)
}
RequestForSlowResponse::RequestForSlowResponse(const RequestForSlowResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:prototask.RequestForSlowResponse)
}

inline void RequestForSlowResponse::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.time_in_seconds_to_sleep_) { 0u }

  };
}

RequestForSlowResponse::~RequestForSlowResponse() {
  // @@protoc_insertion_point(destructor:prototask.RequestForSlowResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RequestForSlowResponse::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void RequestForSlowResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RequestForSlowResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:prototask.RequestForSlowResponse)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.time_in_seconds_to_sleep_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RequestForSlowResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required uint32 time_in_seconds_to_sleep = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_time_in_seconds_to_sleep(&has_bits);
          _impl_.time_in_seconds_to_sleep_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* RequestForSlowResponse::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:prototask.RequestForSlowResponse)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required uint32 time_in_seconds_to_sleep = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_time_in_seconds_to_sleep(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:prototask.RequestForSlowResponse)
  return target;
}

::size_t RequestForSlowResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:prototask.RequestForSlowResponse)
  ::size_t total_size = 0;

  // required uint32 time_in_seconds_to_sleep = 1;
  if ((_impl_._has_bits_[0] & 0x00000001u) != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_time_in_seconds_to_sleep());
  }
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RequestForSlowResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RequestForSlowResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RequestForSlowResponse::GetClassData() const { return &_class_data_; }


void RequestForSlowResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RequestForSlowResponse*>(&to_msg);
  auto& from = static_cast<const RequestForSlowResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:prototask.RequestForSlowResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_time_in_seconds_to_sleep(from._internal_time_in_seconds_to_sleep());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RequestForSlowResponse::CopyFrom(const RequestForSlowResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:prototask.RequestForSlowResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RequestForSlowResponse::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void RequestForSlowResponse::InternalSwap(RequestForSlowResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);

  swap(_impl_.time_in_seconds_to_sleep_, other->_impl_.time_in_seconds_to_sleep_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RequestForSlowResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_work_2eproto_getter, &descriptor_table_work_2eproto_once,
      file_level_metadata_work_2eproto[4]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace prototask
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::prototask::WrapperMessage*
Arena::CreateMaybeMessage< ::prototask::WrapperMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prototask::WrapperMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::prototask::FastResponse*
Arena::CreateMaybeMessage< ::prototask::FastResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prototask::FastResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::prototask::SlowResponse*
Arena::CreateMaybeMessage< ::prototask::SlowResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prototask::SlowResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::prototask::RequestForFastResponse*
Arena::CreateMaybeMessage< ::prototask::RequestForFastResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prototask::RequestForFastResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::prototask::RequestForSlowResponse*
Arena::CreateMaybeMessage< ::prototask::RequestForSlowResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::prototask::RequestForSlowResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
